### ISSUE TITLE
Feature Request: Delay UI/tracker for combat tracker module compatibility

### ISSUE THREAD

**Issue by GorgoPrimus** [oWave/pf2e-flatcheck-helper#16]
I know it's probably a long shot to request a feature for this to function with someone else's unrelated mod, but given how ubiquitous Idle's ITT was which HUD is replacing, it'd be really cool if you could figure out and implement a way to get this to also work with that module's tracker so that we can use that instead of having to turn that off in order to use this.

Thanks for reading either way. This module's awesome.

**Comment by oWave** [comment]
I'm still against direct integration with other combat trackers (see #6).
Both the button in the token HUD (the menu when right-clicking a token) and just using the delay action were added as alternatives to the button in the combat tracker. But using the action could use more work, and that integrates nicely with pf2e HUD since you can drag the action to create a shortcut.

I'll try to clean up the "just use the delay action" part of the code, and maybe knock out #10 while I'm at it.

**Comment by GorgoPrimus** [comment]
Alright, fair enough. Thanks for taking the time to read and respond, and for your work.

**Comment by oWave** [comment]
I cleaned up the "use the delay action to delay/return". The code now just checks the action slug (has to be "delay").
You can add an action (or import the system's delay action) to your character and add that to the HUD. Name/Description can be changed. You probably just want a blank description to not clutter that chat.

I'm leaving this open because the idea of making a custom UI element for delaying is still something I want to try. Would solve the compatibility issues with all combat tracker modules.

**Comment by oWave** [comment]
Idle added delaying to the PF2e HUD combat tracker, but for GMs only. v0.10 includes a setting to modify that module's tracker, making delaying there and in the core tracker but use my implementation.

"If a module includes delaying, I'll try to support it" seems like a reasonable path going forward.
